<a href="https://colab.research.google.com/github/L1NEA/PythonPanda2023.01/blob/main/Pandas01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Primeiro exemplo de manipulação de dados usando Python Pandas**

Autor: Aline Cerqueira

Data: 06 de fevereiro de 2023

In [1]:
# para instalar a biblioteca do Pandas:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [2]:
# Importando Biblioteca Pandas no Python (não é uma biblioteca nativa do Python; o Colab ja tem ela instalada por padrão, mas em um IDE Local precisa instalar a biblioteca)

import pandas as pd

combustiveis_df = pd.read_excel("ca-2021-02.xlsx")

In [3]:
# Usa o print para ver o dataframe!

print(combustiveis_df)

       Regiao - Sigla Estado - Sigla  Municipio  \
0                  NE             AL  ARAPIRACA
1                  NE             AL  ARAPIRACA
2                  NE             AL  ARAPIRACA
3                  NE             AL  ARAPIRACA
4                  NE             AL  ARAPIRACA
...               ...            ...        ...
168404             NE             BA     JEQUIE
168405             SE             MG  ITUIUTABA
168406             SE             MG  ITUIUTABA
168407             SE             MG  ITUIUTABA
168408             SE             MG  ITUIUTABA

                                           Revenda      CNPJ da Revenda  \
0                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
1                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
2                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
3                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
4                             POSTO ARAPIRACA LTDA   12.451.076/0004-65
...                                            ...                  ...
168404  COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA   28.629.089/0001-79
168405           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168406           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168407           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38
168408           ABC DISTRIBUICAO DE PETROLEO LTDA   13.117.591/0006-38

                                      Nome da Rua Numero Rua Complemento  \
0                                  RODOVIA AL 220        105       KM 68
1                                  RODOVIA AL 220        105       KM 68
2                                  RODOVIA AL 220        105       KM 68
3                                  RODOVIA AL 220        105       KM 68
4                                  RODOVIA AL 220        105       KM 68
...                                           ...        ...         ...
168404                  AVENIDA T LOT JD TROPICAL         53         NaN
168405  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168406  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168407  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN
168408  AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA       2415         NaN

             Bairro        Cep             Produto Data da Coleta  \
0       CANAFISTULA  57302-605            GASOLINA     2021-11-01
1       CANAFISTULA  57302-605              ETANOL     2021-11-01
2       CANAFISTULA  57302-605              DIESEL     2021-11-01
3       CANAFISTULA  57302-605  GASOLINA ADITIVADA     2021-11-01
4       CANAFISTULA  57302-605          DIESEL S10     2021-11-01
...             ...        ...                 ...            ...
168404     TROPICAL  45209-130              ETANOL     2021-12-31
168405     ALVORADA  38307-113            GASOLINA     2021-12-31
168406     ALVORADA  38307-113              ETANOL     2021-12-31
168407     ALVORADA  38307-113          DIESEL S10     2021-12-31
168408     ALVORADA  38307-113  GASOLINA ADITIVADA     2021-12-31

        Valor de Venda  Valor de Compra Unidade de Medida       Bandeira
0                6.799              NaN        R$ / litro  VIBRA ENERGIA
1                5.299              NaN        R$ / litro  VIBRA ENERGIA
2                5.549              NaN        R$ / litro  VIBRA ENERGIA
3                6.899              NaN        R$ / litro  VIBRA ENERGIA
4                5.649              NaN        R$ / litro  VIBRA ENERGIA
...                ...              ...               ...            ...
168404           5.859              NaN        R$ / litro     PETROSERRA
168405           6.580              NaN        R$ / litro         BRANCA
168406           4.740              NaN        R$ / litro         BRANCA
168407           5.448              NaN        R$ / litro         BRANCA
168408           6.580              NaN        R$ / litro         BRANCA

[168409 rows x 16 columns]

In [4]:
display (combustiveis_df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,2021-12-31,5.859,NaN,R$ / litro,PETROSERRA
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,2021-12-31,4.740,NaN,R$ / litro,BRANCA
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,2021-12-31,5.448,NaN,R$ / litro,BRANCA
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,2021-12-31,6.580,NaN,R$ / litro,BRANCA

In [5]:
# Exibe as primeiras 5 linhas

display (combustiveis_df.head())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA

In [6]:
# Quero na verdade exibir as 15 primeiras linhas
display (combustiveis_df.head(15))

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA
5,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.198,NaN,R$ / litro,VIBRA ENERGIA
6,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.982,NaN,R$ / litro,VIBRA ENERGIA
7,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.974,NaN,R$ / litro,VIBRA ENERGIA
8,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,GASOLINA ADITIVADA,2021-11-01,7.208,NaN,R$ / litro,VIBRA ENERGIA
9,NE,AL,DELMIRO GOUVEIA,AUTO POSTO FREITAS & MAIA LTDA,12.436.978/0001-80,RUA FLORIANO PEIXOTO,247,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.983,NaN,R$ / litro,VIBRA ENERGIA
10,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,GASOLINA,2021-11-01,7.197,NaN,R$ / litro,BRANCA
11,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,ETANOL,2021-11-01,5.987,NaN,R$ / litro,BRANCA
12,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL,2021-11-01,5.978,NaN,R$ / litro,BRANCA
13,NE,AL,DELMIRO GOUVEIA,AUTO POSTO DA PEDRA LTDA,05.518.639/0001-87,RUA FLORIANO PEIXOTO,281,NaN,CENTRO,57480-000,DIESEL S10,2021-11-01,5.989,NaN,R$ / litro,BRANCA
14,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,04.431.113/0001-00,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,GASOLINA,2021-11-01,7.175,NaN,R$ / litro,BRANCA

In [7]:
# Comand Dataframe.shape

print (combustiveis_df.shape)
# Saída = número de linhas, número de colunas

print (combustiveis_df.shape[0])
# Saída = só o número de linhas

print (combustiveis_df.shape[1])
# Saída = só o número de colunas

(168409, 16)
168409
16

In [8]:
# Mostra as colunas (nomes) e que tipo de dados cada uma tem

print (combustiveis_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 20.6+ MB
None

In [9]:
# Comando Dataframe.describe()

display (combustiveis_df.describe())

# Saída = estatisticas mais básicas do Dataframe (somente informações numéricas) (Contagem de linhas, média, desvio padrão, "parcelas" e máximo)

       Valor de Venda  Valor de Compra
count   168409.000000              0.0
mean         6.005184              NaN
std          0.794541              NaN
min          2.849000              NaN
25%          5.339000              NaN
50%          5.859000              NaN
75%          6.699000              NaN
max          8.990000              NaN

In [10]:
# Filtrar apenas por uma coluna

display(combustiveis_df['Revenda'])

0                               POSTO ARAPIRACA LTDA
1                               POSTO ARAPIRACA LTDA
2                               POSTO ARAPIRACA LTDA
3                               POSTO ARAPIRACA LTDA
4                               POSTO ARAPIRACA LTDA
                             ...
168404    COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA
168405             ABC DISTRIBUICAO DE PETROLEO LTDA
168406             ABC DISTRIBUICAO DE PETROLEO LTDA
168407             ABC DISTRIBUICAO DE PETROLEO LTDA
168408             ABC DISTRIBUICAO DE PETROLEO LTDA
Name: Revenda, Length: 168409, dtype: object

In [11]:
# Criar um novo Dataframe apenas com as colunas que eu quero de outro Dataframe

ca_df = combustiveis_df[['Revenda','Municipio','Produto','Valor de Venda']]
display (ca_df)

,Revenda,Municipio,Produto,Valor de Venda
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799
1,POSTO ARAPIRACA LTDA,ARAPIRACA,ETANOL,5.299
2,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL,5.549
3,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA ADITIVADA,6.899
4,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL S10,5.649
...,...,...,...,...
168404,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,ETANOL,5.859
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580
168406,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,ETANOL,4.740
168407,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,DIESEL S10,5.448
168408,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA ADITIVADA,6.580

In [12]:
# Exibe a 4ª linha

display (ca_df.loc[3])

Revenda           POSTO ARAPIRACA LTDA
Municipio                    ARAPIRACA
Produto             GASOLINA ADITIVADA
Valor de Venda                   6.899
Name: 3, dtype: object

In [13]:
# Exibir da 10ª linha até a 20ª linha

display(ca_df.loc[9:19])

,Revenda,Municipio,Produto,Valor de Venda
9,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.983
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,GASOLINA,7.197
11,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,ETANOL,5.987
12,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,DIESEL,5.978
13,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.989
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA,7.175
15,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,ETANOL,5.930
16,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,DIESEL,5.955
17,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA ADITIVADA,7.175
18,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,DIESEL S10,5.980
19,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,GASOLINA,6.990

In [14]:
# Exibir da 2ª linha até a 10ª pulando de 2 em 2

display(ca_df.loc[2:10:2])

,Revenda,Municipio,Produto,Valor de Venda
2,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL,5.549
4,POSTO ARAPIRACA LTDA,ARAPIRACA,DIESEL S10,5.649
6,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,ETANOL,5.982
8,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,GASOLINA ADITIVADA,7.208
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,GASOLINA,7.197

In [15]:
# Criar um dataframe gas_df contendo apenas as 4 colunas (Revenda, Municipio, Produto, Valor de Venda) somente com combustivel sendo GASOLINA e exibir na tela

gas_df = ca_df.loc[ca_df['Produto'] == 'GASOLINA']
display (gas_df)

,Revenda,Municipio,Produto,Valor de Venda
0,POSTO ARAPIRACA LTDA,ARAPIRACA,GASOLINA,6.799
5,AUTO POSTO FREITAS & MAIA LTDA,DELMIRO GOUVEIA,GASOLINA,7.198
10,AUTO POSTO DA PEDRA LTDA,DELMIRO GOUVEIA,GASOLINA,7.197
14,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,DELMIRO GOUVEIA,GASOLINA,7.175
19,MARCOS ANTONIO DA SILVA CABRAL,ITACOATIARA,GASOLINA,6.990
...,...,...,...,...
168392,AUTO POSTO KM BAURU LTDA,BAURU,GASOLINA,6.199
168394,COOPERCITRUS COOPERATIVA DE PRODUTORES RURAIS,ITUIUTABA,GASOLINA,6.899
168399,VICMAR COMERCIO DE COMBUSTIVEIS E LUBRIFICANTE...,CAMPOS DOS GOYTACAZES,GASOLINA,7.090
168403,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,JEQUIE,GASOLINA,6.799
168405,ABC DISTRIBUICAO DE PETROLEO LTDA,ITUIUTABA,GASOLINA,6.580

In [16]:
# Mostrar o valor da gasolina mais cara

display (gas_df['Valor de Venda'].max())

7.999

In [17]:
# Mostrar posto e municipio da gasolina mais cara

display(gas_df[['Revenda', 'Municipio', 'Valor de Venda']].max())

Revenda           ZV POSTO DE SERVIÇO LTDA.
Municipio                           XANXERE
Valor de Venda                        7.999
dtype: object

In [23]:
# Dataframe.loc[] com multiplas condições para filtragem

# Quais são os preços dos postos que vendem ETANOL na cidade de SANTO ANDRE ordenado do menor -> maior

etanol_santoandre_df = ca_df.loc[(ca_df ['Produto'] == 'ETANOL') & (ca_df ['Municipio'] == 'SANTO ANDRE')]
display (etanol_santoandre_df.sort_values(by='Valor de Venda'))

,Revenda,Municipio,Produto,Valor de Venda
151696,AUTO POSTO CENTREVILLE LTDA,SANTO ANDRE,ETANOL,4.489
135731,AUTO POSTO X6 SANTO ANDRÉ LTDA.,SANTO ANDRE,ETANOL,4.499
136302,PATTO ROSA AUTO POSTO LTDA,SANTO ANDRE,ETANOL,4.599
133248,POSTO DE SERVICOS REQUINTE COMERCIO DE COMBUST...,SANTO ANDRE,ETANOL,4.697
154565,AUTO POSTO CAPITAO BRASIL II LTDA.,SANTO ANDRE,ETANOL,4.699
...,...,...,...,...
77056,ALVORECER AUTO POSTO LTDA,SANTO ANDRE,ETANOL,5.599
77061,AUTO POSTO DON PEPE,SANTO ANDRE,ETANOL,5.799
1519,AUTO POSTO ALEMAO LTDA - EPP,SANTO ANDRE,ETANOL,5.799
43572,AUTO POSTO ALEMAO LTDA - EPP,SANTO ANDRE,ETANOL,5.799
20235,AUTO POSTO DON PEPE,SANTO ANDRE,ETANOL,5.799

In [30]:
# Qual é a média de preço dos combustíveis GASOLINA e GASOLINA ADITIVADA do bairro VILA FORMOSA em SÃO PAULO
display (combustiveis_df.loc[(combustiveis_df['Bairro'] == 'VILA FORMOSA') &
                             (combustiveis_df ['Municipio'] == 'SAO PAULO') &
                             ((combustiveis_df ['Produto'] == 'GASOLINA') | (combustiveis_df ['Produto'] == 'GASOLINA ADITIVADA')),
                             ['Valor de Venda']].mean())

Valor de Venda    6.501764
dtype: float64

In [40]:
# Como mostrar média de valor POR COMBUSTÍVEL

media_por_combustivel_df = ca_df[['Produto','Valor de Venda']].groupby(by= 'Produto').mean().round(2)
display(media_por_combustivel_df)

                    Valor de Venda
Produto
DIESEL                        5.38
DIESEL S10                    5.45
ETANOL                        5.46
GASOLINA                      6.71
GASOLINA ADITIVADA            6.86
GNV                           4.39

In [41]:
# Adicionar uma coluna de valor booleano no combustiveis_df chamada "Ativo" que, por padrão, vai ser True para TODAS as linhas

combustiveis_df ['Ativo'] = True
print (combustiveis_df.info())
display (combustiveis_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(13)
memory usage: 20.7+ MB
None

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA,True
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA,True
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA,True
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA,True
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA,True

In [44]:
# Criar uma coluna nova chamada "Obs" que preencha automaticamente "MELHOR CIDADE" quando o municipio for SAO PAULO

combustiveis_df['Obs'] = ["Melhor Cidade" if municipio == 'SAO PAULO' else '' for municipio in combustiveis_df['Municipio']]
print (combustiveis_df.info())
display (combustiveis_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168409 entries, 0 to 168408
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     168409 non-null  object
 1   Estado - Sigla     168409 non-null  object
 2   Municipio          168409 non-null  object
 3   Revenda            168409 non-null  object
 4   CNPJ da Revenda    168409 non-null  object
 5   Nome da Rua        168409 non-null  object
 6   Numero Rua         168353 non-null  object
 7   Complemento        35057 non-null   object
 8   Bairro             168043 non-null  object
 9   Cep                168409 non-null  object
 10  Produto            168409 non-null  object
 11  Data da Coleta     168409 non-null  datetime64[ns]
 12  Valor de Venda     168409 non-null  float64
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  168409 non-null  object
 15  Bandeira           168409 non-null  object
 16  Ativo              168409 non-null  bool
 17  Obs                168409 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(2), object(14)
memory usage: 22.0+ MB
None

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,Ativo,Obs
0,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA,2021-11-01,6.799,NaN,R$ / litro,VIBRA ENERGIA,True,
1,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,ETANOL,2021-11-01,5.299,NaN,R$ / litro,VIBRA ENERGIA,True,
2,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL,2021-11-01,5.549,NaN,R$ / litro,VIBRA ENERGIA,True,
3,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,GASOLINA ADITIVADA,2021-11-01,6.899,NaN,R$ / litro,VIBRA ENERGIA,True,
4,NE,AL,ARAPIRACA,POSTO ARAPIRACA LTDA,12.451.076/0004-65,RODOVIA AL 220,105,KM 68,CANAFISTULA,57302-605,DIESEL S10,2021-11-01,5.649,NaN,R$ / litro,VIBRA ENERGIA,True,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168404,NE,BA,JEQUIE,COMERCIAL DE COMBUSTIVEL CACHOEIRINHA LTDA,28.629.089/0001-79,AVENIDA T LOT JD TROPICAL,53,NaN,TROPICAL,45209-130,ETANOL,2021-12-31,5.859,NaN,R$ / litro,PETROSERRA,True,
168405,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA,2021-12-31,6.580,NaN,R$ / litro,BRANCA,True,
168406,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,ETANOL,2021-12-31,4.740,NaN,R$ / litro,BRANCA,True,
168407,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,DIESEL S10,2021-12-31,5.448,NaN,R$ / litro,BRANCA,True,
168408,SE,MG,ITUIUTABA,ABC DISTRIBUICAO DE PETROLEO LTDA,13.117.591/0006-38,AVENIDA PROFESSOR JOSE VIEIRA DE MENDONCA,2415,NaN,ALVORADA,38307-113,GASOLINA ADITIVADA,2021-12-31,6.580,NaN,R$ / litro,BRANCA,True,

In [47]:
# Exportar para excel o dataframecom etanol em Santo Andre
etanol_santoandre_df.to_excel('etanol_santoandre.xlsx', sheet_name = 'Etanol em Santo Andre')